# -*-org-*- ; Time-stamp: <2013-01-13 00:42:17 leo>


The softwares I need to be able to "operate" properly.

* emacs                                                                :text:
  What else? And the version must be at least 24
  Dependencies: emacs
* programming                                                   :programming:
** guake                                                           :terminal:
  A simple terminal emulator, easy to access.
  Dependencies: guake
** doxygen                                                    :documentation:
   A very powerful tool to generate doc from javadoc style
   comment. Works with many languages.
   Dependencies: doxygen
** subversion                                                   :versionning:
   Sometimes I work with people using svn. Not my thing but hey, it
   works too!
   Dependencies: subversion
** git                                                          :versionning:
   My favorite version manager system. Perfect since my projects are
   hosted on github anyway.
   Dependencies: git
* crypto                                                             :crypto:
** keepassx
   Awesome to store and retrieve easily password and other top-secret
   data.
   Dependencies: keepassx
** enigmail
   I sign my mails using GPG and don't like doing it by hand. It is a
   thunderbird extension.
   Dependencies: enigmail
* LaTeX                                                         :typesetting:
  LaTeX, *the* text formatting sofware. I use plenty of
  sub-packages, the aim is to add them here as soon as I download
  them to remember.
** Basic installation                                               :package:
   Granted, I want the basic stuff: latex and bibtex.
   Dependencies: texlive-latex-base biblatex texlive-generic-extra
   Dependencies: texlive-latex-recommended texlive-extra-utils
** Math related                                                     :package:
   I do math (hopefully as a living at some point), so I need these.
   Dependencies: texlive-math-extra texlive-science
** Miscellaneous packages                                           :package:
   + Beamer allows to make presentations, which is important.
     Dependencies: latex-beamer
   + Auctex, when used with emacs, simply rocks.
     Dependencies: auctex
   + Sometimes I write in French, in which case xelatex is a better
     option.
     Dependencies: texlive-xete
   + Adding pictures are nice
     Dependencies: texlive-pictures

* Media readers                                                       :media:
** vlc
   Because vlc. Period.
   Dependencies: vlc
